all:
  hosts:
    code-server-droplet:
      ansible_host: 188.166.233.61
      ansible_connection: ssh
      ansible_user: root
      ansible_ssh_private_key_file: /home/fred/tmp/mykey
      public_key: /home/fred/tmp/mykey.pub
      cs_password: changeit