- name: Install Stuff
  hosts: all
  become: yes 
  vars:
   download_dir: '/usr/local/opt'
   mysql_directory: 'mysql-8.0.26-linux-glibc2.12-x86_64'
   dl_url: 'https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.26-linux-glibc2.12-x86_64.tar.xz'
   grp_user_name: 'mysql'
   apt_pkgs_to_install: ['ca-certificates', 'gnupg', 'lsb-release']
   dockeransible_pkgs_to_install: ['ansible', 'docker-ce', 'docker-ce-cli', 'containerd.io']
   pkgs_to_install: ['libaio1', 'libtinfo5']
   mysql_base_dir: '/usr/local/opt/mysql'
  tasks:  
  - name: Install the following packages - unzip, libaio1, libtinfo5
    apt:
      update_cache: yes
      name: "{{ item }}"
      state: latest
    loop: "{{ pkgs_to_install }}"
    register: result
  - name: Packer Add the HashiCorp GPG key.
    shell: 'curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -'
  - name: Packer Add the official HashiCorp Linux repository
    shell: 'sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"'
  - name: Packer Update and install
    shell: 'sudo apt-get update && sudo apt-get install packer'
  - name: Docker update the apt package index and install packages to allow apt to use a repository over HTTPS
    apt:
      update_cache: yes
      name: "{{ item }}"
      state: latest
    loop: "{{ apt_pkgs_to_install }}"
    register: result
  - name: Docker add apt key
    apt_key:
      url: " https://download.docker.com/linux/ubuntu/gpg"
      state: present
  - name: Ansible Add repositories
    apt_repository:
      repo: "{{ item }}"
      state: present
    loop:
      - "ppa:ansible/ansible"
      - "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  - name: Docker install docker
    apt:
      update_cache: yes
      name: "{{ item }}"
      state: latest
    loop: "{{ dockeransible_pkgs_to_install }}"
  - name: Nginx install
    apt:
      update_cache: yes
      name: "nginx"
      state: latest
  - name: Create user fred
    user: 
      name: fred
      shell: /bin/bash
      groups: docker,sudo
      append: yes
      state: present
  - name: add ssh keys to fred
    authorized_key:
      user: fred
      state: present
      key: "{{ lookup('file', './mykey.pub') }}"
  - name: add instructor's SSH key
    authorized_key:
      user: fred
      state: present
      key: https://drive.google.com/u/0/uc?id=17pBBYJhRkyrfVhLu44e23CA2PbeXPuMg&export=download